DRONE_MAX_ACCEL = 1
DRONE_MAX_SPEED = 1
DRONE_MAX_DIST = 2
#DRONE_MAX_DIST = 150
ACCEL_STEP = 0.25
SPEED_STEP = 0.25
DIST_STEP = 0.25
#ACCEL_STEP = 0.1
#SPEED_STEP = 0.1
#DIST_STEP = 0.1

DIST_VARIANCE = 1
SPEED_VARIANCE = 0.1

#DIST_VARIANCE = 1
#SPEED_VARIANCE = 1
